# compose.yml
version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: music
    ports:
      - "5432:5432"
    volumes:
       - ../data:/var/lib/postgresql/data