# compose.yml
version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: music
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data
    networks:
      - cronpg_network

  
  cronpg:
    build: 
      context: ./cronpg
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /mnt/win_Music/iTunes:/mnt/win_Music/iTunes
    depends_on: 
      - db
    networks:
      - cronpg_network

networks:
  cronpg_network:
    driver: bridge
